# Generated by Django 3.2.5 on 2021-07-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='degrees',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='image',
            new_name='temperature',
        ),
    ]
