# Generated by Django 3.2.5 on 2021-07-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlModel',
            new_name='Url',
        ),
    ]
