# Generated by Django 3.2.4 on 2021-06-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_completed_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='memory',
            new_name='memo',
        ),
    ]
